import imageOne from "../../../../assets/img/pixasquare-4ojhpgKpS68-unsplash.jpg";
import imageTwo from "../../../../assets/img/webaliser-_TPTXZd9mOo-unsplash.jpg";
import imageThree from "../../../../assets/img/cindy-tang-ob-hsLNxYPc-unsplash.jpg";
import imageFour from "../../../../assets/img/naomi-hebert-MP0bgaS_d1c-unsplash.jpg";

export const tileData = [
	{
		img: imageOne,
		title: "Mansión Spencer. Montañas Arklay",
		description:
			"Construida en 1950. Forma parte de los suburbios del sector Norte de Raccoon City",
		available: "Disponible",
		id: "3523",
		kindHouse: "Departamento",
		location: "País",
		amountOf: {
			toilets: "3",
			bedroom: "5",
			suites: "2",
		},
		acient: "70 años",
		spaceWithAccount: "6",
		artefactWithAccount: "5",
		adeheredServices: ["Luz", "Agua", "Internet"],
		owerDetails: {
			numberId: "EF4563",
			kind: "Corporativo",
			firstname: "Jill",
			surname: "Valentine",
			dni: "37987213",
			phone: "+54-98760723",
			email: "jill@start.com",
			address: "Raccoon City 345",
		},
		contractOptions: "Venta",
	},
	{
		img: imageThree,
		title: "Sector F Complejo Lambda Black Mesa",
		description:
			"Es uno de los siete sectores principales del Black Mesa Research Facility.",
		available: "Disponible",
		id: "3523",
		kindHouse: "No Departamento",
		location: "País",
		amountOf: {
			toilets: "3",
			bedroom: "5",
			suites: "2",
		},
		acient: "70 años",
		spaceWithAccount: "6",
		artefactWithAccount: "5",
		adeheredServices: ["Luz", "Agua", "Internet"],
		owerDetails: {
			numberId: "EF4563",
			kind: "Corporativo",
			firstname: "Jill",
			surname: "Valentine",
			dni: "37987213",
			phone: "+54-98760723",
			email: "jill@start.com",
			address: "Raccoon City 345",
		},
		contractOptions: "Venta",
	},
	{
		img: imageFour,
		title: "Mansión Spencer. Montañas Arklay",
		description:
			"Construida en 1950. Forma parte de los suburbios del sector Norte de Raccoon City",
		available: "Disponible",
		id: "3523",
		kindHouse: "Departamento",
		location: "País",
		amountOf: {
			toilets: "3",
			bedroom: "5",
			suites: "2",
		},
		acient: "70 años",
		spaceWithAccount: "6",
		artefactWithAccount: "5",
		adeheredServices: ["Luz", "Agua", "Internet"],
		owerDetails: {
			numberId: "EF4563",
			kind: "Corporativo",
			firstname: "Jill",
			surname: "Valentine",
			dni: "37987213",
			phone: "+54-98760723",
			email: "jill@start.com",
			address: "Raccoon City 345",
		},
		contractOptions: "Venta",
	},
	{
		img: imageTwo,
		title: "Mansión Spencer. Montañas Arklay",
		description:
			"Construida en 1950. Forma parte de los suburbios del sector Norte de Raccoon City",
		available: "Disponible",
		id: "3523",
		kindHouse: "Departamento",
		location: "País",
		amountOf: {
			toilets: "3",
			bedroom: "5",
			suites: "2",
		},
		acient: "70 años",
		spaceWithAccount: "6",
		artefactWithAccount: "5",
		adeheredServices: ["Luz", "Agua", "Internet"],
		owerDetails: {
			numberId: "EF4563",
			kind: "Corporativo",
			firstname: "Jill",
			surname: "Valentine",
			dni: "37987213",
			phone: "+54-98760723",
			email: "jill@start.com",
			address: "Raccoon City 345",
		},
		contractOptions: "Venta",
	},
];
